version: 2
updates:
  - package-ecosystem: "npm" # Ecosistema de paquetes
    directory: "/" # Ubicación de los manifiestos del paquete
    schedule:
      interval: "daily" # Cambiado a diario
      time: "00:00" # Hora a medianoche en UTC
